#!/usr/bin/env node
// Builds the static site from src/ into the repo root.
//
// - index.html            <- src/data/site.js + src/components/*.js
// - assets/css/style.css  <- src/styles/*.css (concatenated in filename order)
// - assets/js/main.js     <- src/scripts/*.js (concatenated in filename order)
//
// GitHub Pages just serves whatever's committed, so run `npm run build`
// after editing anything under src/ and commit the generated output too.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { site } from '../src/data/site.js';
import { renderLayout } from '../src/components/layout.js';
import { renderHeader } from '../src/components/header.js';
import { renderHero } from '../src/components/hero.js';
import { renderAbout } from '../src/components/about.js';
import { renderExperience } from '../src/components/experience.js';
import { renderWork } from '../src/components/work.js';
import { renderSkills } from '../src/components/skills.js';
import { renderEducation } from '../src/components/education.js';
import { renderContact } from '../src/components/contact.js';
import { renderFooter } from '../src/components/footer.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const GENERATED_NOTICE_HTML = '<!-- Generated by tools/build.js from src/ — edit there, then run `npm run build`. -->';
const GENERATED_NOTICE_CSS = '/* Generated by tools/build.js from src/styles/ — edit there, then run `npm run build`. */';
const GENERATED_NOTICE_JS = '// Generated by tools/build.js from src/scripts/ — edit there, then run `npm run build`.';

function concatDir(relDir, ext) {
  const dir = join(root, relDir);
  const files = readdirSync(dir).filter((f) => f.endsWith(ext)).sort();
  return files.map((f) => readFileSync(join(dir, f), 'utf8').trimEnd()).join('\n\n');
}

function buildHtml() {
  const main = [
    renderHero(site.hero),
    renderAbout(site.about),
    renderExperience(site.experience),
    renderWork(site.work),
    renderSkills(site.skills),
    renderEducation(site.education),
    renderContact(site.contact),
  ].join('\n\n');

  const document = renderLayout(site, {
    header: renderHeader({ brand: site.brand, nav: site.nav }),
    main,
    footer: renderFooter(site.footer),
  });

  // Notice goes right after <!doctype html>, never before it — a comment
  // before the doctype can push older browsers into quirks mode.
  const withNotice = document.replace('<!doctype html>', `<!doctype html>\n${GENERATED_NOTICE_HTML}`);

  writeFileSync(join(root, 'index.html'), withNotice);
  console.log('wrote index.html');
}

function buildCss() {
  const css = `${GENERATED_NOTICE_CSS}\n\n${concatDir('src/styles', '.css')}\n`;
  writeFileSync(join(root, 'assets/css/style.css'), css);
  console.log('wrote assets/css/style.css');
}

function buildJs() {
  const js = `${GENERATED_NOTICE_JS}\n\n${concatDir('src/scripts', '.js')}\n`;
  writeFileSync(join(root, 'assets/js/main.js'), js);
  console.log('wrote assets/js/main.js');
}

buildHtml();
buildCss();
buildJs();
